# .github/workflows/ci-push.yaml
name: Release on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for the release job to push back docs/

jobs:
  lint-test:
    name: Lint & Test Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint changed charts
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint \
            --validate-maintainers=false \
            --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Install changed charts
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }}

  release:
    name: Package & Publish Helm Chart
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Package Helm chart(s)
        run: |
          mkdir -p docs
          helm package ./chart -d docs

      - name: Re-generate Helm repo index
        run: |
          helm repo index docs \
            --url https://iMash-io.github.io/supabase-k8-helm \
            --merge docs/index.yaml

      - name: Commit & push docs/
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: publish Helm chart packages [skip ci]"
          file_pattern: docs/**
